# Generated by Django 5.0.2 on 2024-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
