# Generated by Django 5.0.2 on 2024-02-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
    ]
